/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerRouteRouteImport } from './routes/customer/route'
import { Route as DesignRouteImport } from './routes/design'
import { Route as MerchantRouteRouteImport } from './routes/merchant/route'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as StatusRouteImport } from './routes/status'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as CustomerConnectionIdRouteImport } from './routes/customer/$connectionId'
import { Route as CustomerCardRouteImport } from './routes/customer/card'
import { Route as MerchantIndexRouteImport } from './routes/merchant/index'
import { Route as MerchantConnectionIdRouteImport } from './routes/merchant/$connectionId'
import { Route as MerchantNewRouteImport } from './routes/merchant/new'
import { Route as MerchantRecordRouteImport } from './routes/merchant/record'
import { Route as MerchantScanRouteImport } from './routes/merchant/scan'
import { Route as MerchantSettingsRouteImport } from './routes/merchant/settings'
import { Route as PrototypeLandingRouteImport } from './routes/prototype/landing'
import { Route as PrototypeShellRouteImport } from './routes/prototype/shell'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CustomerApproveTransactionIdRouteImport } from './routes/customer/approve/$transactionId'
import { Route as CustomerPayConnectionIdRouteImport } from './routes/customer/pay/$connectionId'
import { Route as MerchantTermsConnectionIdRouteImport } from './routes/merchant/terms/$connectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRouteRoute = CustomerRouteRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRouteRoute = MerchantRouteRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerConnectionIdRoute = CustomerConnectionIdRouteImport.update({
  id: '/$connectionId',
  path: '/$connectionId',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerCardRoute = CustomerCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantConnectionIdRoute = MerchantConnectionIdRouteImport.update({
  id: '/$connectionId',
  path: '/$connectionId',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantNewRoute = MerchantNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantRecordRoute = MerchantRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantScanRoute = MerchantScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantSettingsRoute = MerchantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const PrototypeLandingRoute = PrototypeLandingRouteImport.update({
  id: '/prototype/landing',
  path: '/prototype/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeShellRoute = PrototypeShellRouteImport.update({
  id: '/prototype/shell',
  path: '/prototype/shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerApproveTransactionIdRoute =
  CustomerApproveTransactionIdRouteImport.update({
    id: '/approve/$transactionId',
    path: '/approve/$transactionId',
    getParentRoute: () => CustomerRouteRoute,
  } as any)
const CustomerPayConnectionIdRoute = CustomerPayConnectionIdRouteImport.update({
  id: '/pay/$connectionId',
  path: '/pay/$connectionId',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const MerchantTermsConnectionIdRoute =
  MerchantTermsConnectionIdRouteImport.update({
    id: '/terms/$connectionId',
    path: '/terms/$connectionId',
    getParentRoute: () => MerchantRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteRouteWithChildren
  '/merchant': typeof MerchantRouteRouteWithChildren
  '/design': typeof DesignRoute
  '/sign-in': typeof SignInRoute
  '/status': typeof StatusRoute
  '/welcome': typeof WelcomeRoute
  '/api/events': typeof ApiEventsRoute
  '/customer/$connectionId': typeof CustomerConnectionIdRoute
  '/customer/card': typeof CustomerCardRoute
  '/merchant/$connectionId': typeof MerchantConnectionIdRoute
  '/merchant/new': typeof MerchantNewRoute
  '/merchant/record': typeof MerchantRecordRoute
  '/merchant/scan': typeof MerchantScanRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/prototype/landing': typeof PrototypeLandingRoute
  '/prototype/shell': typeof PrototypeShellRoute
  '/customer/': typeof CustomerIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/customer/approve/$transactionId': typeof CustomerApproveTransactionIdRoute
  '/customer/pay/$connectionId': typeof CustomerPayConnectionIdRoute
  '/merchant/terms/$connectionId': typeof MerchantTermsConnectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/sign-in': typeof SignInRoute
  '/status': typeof StatusRoute
  '/welcome': typeof WelcomeRoute
  '/api/events': typeof ApiEventsRoute
  '/customer/$connectionId': typeof CustomerConnectionIdRoute
  '/customer/card': typeof CustomerCardRoute
  '/merchant/$connectionId': typeof MerchantConnectionIdRoute
  '/merchant/new': typeof MerchantNewRoute
  '/merchant/record': typeof MerchantRecordRoute
  '/merchant/scan': typeof MerchantScanRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/prototype/landing': typeof PrototypeLandingRoute
  '/prototype/shell': typeof PrototypeShellRoute
  '/customer': typeof CustomerIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/customer/approve/$transactionId': typeof CustomerApproveTransactionIdRoute
  '/customer/pay/$connectionId': typeof CustomerPayConnectionIdRoute
  '/merchant/terms/$connectionId': typeof MerchantTermsConnectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteRouteWithChildren
  '/merchant': typeof MerchantRouteRouteWithChildren
  '/design': typeof DesignRoute
  '/sign-in': typeof SignInRoute
  '/status': typeof StatusRoute
  '/welcome': typeof WelcomeRoute
  '/api/events': typeof ApiEventsRoute
  '/customer/$connectionId': typeof CustomerConnectionIdRoute
  '/customer/card': typeof CustomerCardRoute
  '/merchant/$connectionId': typeof MerchantConnectionIdRoute
  '/merchant/new': typeof MerchantNewRoute
  '/merchant/record': typeof MerchantRecordRoute
  '/merchant/scan': typeof MerchantScanRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/prototype/landing': typeof PrototypeLandingRoute
  '/prototype/shell': typeof PrototypeShellRoute
  '/customer/': typeof CustomerIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/customer/approve/$transactionId': typeof CustomerApproveTransactionIdRoute
  '/customer/pay/$connectionId': typeof CustomerPayConnectionIdRoute
  '/merchant/terms/$connectionId': typeof MerchantTermsConnectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer'
    | '/merchant'
    | '/design'
    | '/sign-in'
    | '/status'
    | '/welcome'
    | '/api/events'
    | '/customer/$connectionId'
    | '/customer/card'
    | '/merchant/$connectionId'
    | '/merchant/new'
    | '/merchant/record'
    | '/merchant/scan'
    | '/merchant/settings'
    | '/prototype/landing'
    | '/prototype/shell'
    | '/customer/'
    | '/merchant/'
    | '/api/auth/$'
    | '/customer/approve/$transactionId'
    | '/customer/pay/$connectionId'
    | '/merchant/terms/$connectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/sign-in'
    | '/status'
    | '/welcome'
    | '/api/events'
    | '/customer/$connectionId'
    | '/customer/card'
    | '/merchant/$connectionId'
    | '/merchant/new'
    | '/merchant/record'
    | '/merchant/scan'
    | '/merchant/settings'
    | '/prototype/landing'
    | '/prototype/shell'
    | '/customer'
    | '/merchant'
    | '/api/auth/$'
    | '/customer/approve/$transactionId'
    | '/customer/pay/$connectionId'
    | '/merchant/terms/$connectionId'
  id:
    | '__root__'
    | '/'
    | '/customer'
    | '/merchant'
    | '/design'
    | '/sign-in'
    | '/status'
    | '/welcome'
    | '/api/events'
    | '/customer/$connectionId'
    | '/customer/card'
    | '/merchant/$connectionId'
    | '/merchant/new'
    | '/merchant/record'
    | '/merchant/scan'
    | '/merchant/settings'
    | '/prototype/landing'
    | '/prototype/shell'
    | '/customer/'
    | '/merchant/'
    | '/api/auth/$'
    | '/customer/approve/$transactionId'
    | '/customer/pay/$connectionId'
    | '/merchant/terms/$connectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRouteRoute: typeof CustomerRouteRouteWithChildren
  MerchantRouteRoute: typeof MerchantRouteRouteWithChildren
  DesignRoute: typeof DesignRoute
  SignInRoute: typeof SignInRoute
  StatusRoute: typeof StatusRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiEventsRoute: typeof ApiEventsRoute
  PrototypeLandingRoute: typeof PrototypeLandingRoute
  PrototypeShellRoute: typeof PrototypeShellRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/$connectionId': {
      id: '/customer/$connectionId'
      path: '/$connectionId'
      fullPath: '/customer/$connectionId'
      preLoaderRoute: typeof CustomerConnectionIdRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/card': {
      id: '/customer/card'
      path: '/card'
      fullPath: '/customer/card'
      preLoaderRoute: typeof CustomerCardRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/$connectionId': {
      id: '/merchant/$connectionId'
      path: '/$connectionId'
      fullPath: '/merchant/$connectionId'
      preLoaderRoute: typeof MerchantConnectionIdRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/new': {
      id: '/merchant/new'
      path: '/new'
      fullPath: '/merchant/new'
      preLoaderRoute: typeof MerchantNewRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/record': {
      id: '/merchant/record'
      path: '/record'
      fullPath: '/merchant/record'
      preLoaderRoute: typeof MerchantRecordRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/scan': {
      id: '/merchant/scan'
      path: '/scan'
      fullPath: '/merchant/scan'
      preLoaderRoute: typeof MerchantScanRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/settings': {
      id: '/merchant/settings'
      path: '/settings'
      fullPath: '/merchant/settings'
      preLoaderRoute: typeof MerchantSettingsRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/prototype/landing': {
      id: '/prototype/landing'
      path: '/prototype/landing'
      fullPath: '/prototype/landing'
      preLoaderRoute: typeof PrototypeLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/shell': {
      id: '/prototype/shell'
      path: '/prototype/shell'
      fullPath: '/prototype/shell'
      preLoaderRoute: typeof PrototypeShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/approve/$transactionId': {
      id: '/customer/approve/$transactionId'
      path: '/approve/$transactionId'
      fullPath: '/customer/approve/$transactionId'
      preLoaderRoute: typeof CustomerApproveTransactionIdRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/pay/$connectionId': {
      id: '/customer/pay/$connectionId'
      path: '/pay/$connectionId'
      fullPath: '/customer/pay/$connectionId'
      preLoaderRoute: typeof CustomerPayConnectionIdRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/merchant/terms/$connectionId': {
      id: '/merchant/terms/$connectionId'
      path: '/terms/$connectionId'
      fullPath: '/merchant/terms/$connectionId'
      preLoaderRoute: typeof MerchantTermsConnectionIdRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
  }
}

interface CustomerRouteRouteChildren {
  CustomerConnectionIdRoute: typeof CustomerConnectionIdRoute
  CustomerCardRoute: typeof CustomerCardRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerApproveTransactionIdRoute: typeof CustomerApproveTransactionIdRoute
  CustomerPayConnectionIdRoute: typeof CustomerPayConnectionIdRoute
}

const CustomerRouteRouteChildren: CustomerRouteRouteChildren = {
  CustomerConnectionIdRoute: CustomerConnectionIdRoute,
  CustomerCardRoute: CustomerCardRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerApproveTransactionIdRoute: CustomerApproveTransactionIdRoute,
  CustomerPayConnectionIdRoute: CustomerPayConnectionIdRoute,
}

const CustomerRouteRouteWithChildren = CustomerRouteRoute._addFileChildren(
  CustomerRouteRouteChildren,
)

interface MerchantRouteRouteChildren {
  MerchantConnectionIdRoute: typeof MerchantConnectionIdRoute
  MerchantNewRoute: typeof MerchantNewRoute
  MerchantRecordRoute: typeof MerchantRecordRoute
  MerchantScanRoute: typeof MerchantScanRoute
  MerchantSettingsRoute: typeof MerchantSettingsRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
  MerchantTermsConnectionIdRoute: typeof MerchantTermsConnectionIdRoute
}

const MerchantRouteRouteChildren: MerchantRouteRouteChildren = {
  MerchantConnectionIdRoute: MerchantConnectionIdRoute,
  MerchantNewRoute: MerchantNewRoute,
  MerchantRecordRoute: MerchantRecordRoute,
  MerchantScanRoute: MerchantScanRoute,
  MerchantSettingsRoute: MerchantSettingsRoute,
  MerchantIndexRoute: MerchantIndexRoute,
  MerchantTermsConnectionIdRoute: MerchantTermsConnectionIdRoute,
}

const MerchantRouteRouteWithChildren = MerchantRouteRoute._addFileChildren(
  MerchantRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRouteRoute: CustomerRouteRouteWithChildren,
  MerchantRouteRoute: MerchantRouteRouteWithChildren,
  DesignRoute: DesignRoute,
  SignInRoute: SignInRoute,
  StatusRoute: StatusRoute,
  WelcomeRoute: WelcomeRoute,
  ApiEventsRoute: ApiEventsRoute,
  PrototypeLandingRoute: PrototypeLandingRoute,
  PrototypeShellRoute: PrototypeShellRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
