/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignRouteImport } from './routes/design'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as StatusRouteImport } from './routes/status'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as CustomerConnectionIdRouteImport } from './routes/customer/$connectionId'
import { Route as MerchantIndexRouteImport } from './routes/merchant/index'
import { Route as MerchantConnectionIdRouteImport } from './routes/merchant/$connectionId'
import { Route as MerchantNewRouteImport } from './routes/merchant/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerConnectionIdRoute = CustomerConnectionIdRouteImport.update({
  id: '/customer/$connectionId',
  path: '/customer/$connectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/merchant/',
  path: '/merchant/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantConnectionIdRoute = MerchantConnectionIdRouteImport.update({
  id: '/merchant/$connectionId',
  path: '/merchant/$connectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantNewRoute = MerchantNewRouteImport.update({
  id: '/merchant/new',
  path: '/merchant/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/sign-in': typeof SignInRoute
  '/status': typeof StatusRoute
  '/welcome': typeof WelcomeRoute
  '/customer/$connectionId': typeof CustomerConnectionIdRoute
  '/merchant/$connectionId': typeof MerchantConnectionIdRoute
  '/merchant/new': typeof MerchantNewRoute
  '/customer/': typeof CustomerIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/sign-in': typeof SignInRoute
  '/status': typeof StatusRoute
  '/welcome': typeof WelcomeRoute
  '/customer/$connectionId': typeof CustomerConnectionIdRoute
  '/merchant/$connectionId': typeof MerchantConnectionIdRoute
  '/merchant/new': typeof MerchantNewRoute
  '/customer': typeof CustomerIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/sign-in': typeof SignInRoute
  '/status': typeof StatusRoute
  '/welcome': typeof WelcomeRoute
  '/customer/$connectionId': typeof CustomerConnectionIdRoute
  '/merchant/$connectionId': typeof MerchantConnectionIdRoute
  '/merchant/new': typeof MerchantNewRoute
  '/customer/': typeof CustomerIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/sign-in'
    | '/status'
    | '/welcome'
    | '/customer/$connectionId'
    | '/merchant/$connectionId'
    | '/merchant/new'
    | '/customer/'
    | '/merchant/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/sign-in'
    | '/status'
    | '/welcome'
    | '/customer/$connectionId'
    | '/merchant/$connectionId'
    | '/merchant/new'
    | '/customer'
    | '/merchant'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/sign-in'
    | '/status'
    | '/welcome'
    | '/customer/$connectionId'
    | '/merchant/$connectionId'
    | '/merchant/new'
    | '/customer/'
    | '/merchant/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRoute
  SignInRoute: typeof SignInRoute
  StatusRoute: typeof StatusRoute
  WelcomeRoute: typeof WelcomeRoute
  CustomerConnectionIdRoute: typeof CustomerConnectionIdRoute
  MerchantConnectionIdRoute: typeof MerchantConnectionIdRoute
  MerchantNewRoute: typeof MerchantNewRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/customer'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/$connectionId': {
      id: '/customer/$connectionId'
      path: '/customer/$connectionId'
      fullPath: '/customer/$connectionId'
      preLoaderRoute: typeof CustomerConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/merchant'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/$connectionId': {
      id: '/merchant/$connectionId'
      path: '/merchant/$connectionId'
      fullPath: '/merchant/$connectionId'
      preLoaderRoute: typeof MerchantConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/new': {
      id: '/merchant/new'
      path: '/merchant/new'
      fullPath: '/merchant/new'
      preLoaderRoute: typeof MerchantNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  SignInRoute: SignInRoute,
  StatusRoute: StatusRoute,
  WelcomeRoute: WelcomeRoute,
  CustomerConnectionIdRoute: CustomerConnectionIdRoute,
  MerchantConnectionIdRoute: MerchantConnectionIdRoute,
  MerchantNewRoute: MerchantNewRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  MerchantIndexRoute: MerchantIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
