/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerRouteRouteImport } from './routes/customer/route'
import { Route as DesignRouteImport } from './routes/design'
import { Route as MerchantRouteRouteImport } from './routes/merchant/route'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as StatusRouteImport } from './routes/status'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as CustomerConnectionIdRouteImport } from './routes/customer/$connectionId'
import { Route as CustomerCardRouteImport } from './routes/customer/card'
import { Route as CustomerNotificationsRouteImport } from './routes/customer/notifications'
import { Route as InvoiceInvoiceIdRouteImport } from './routes/invoice/$invoiceId'
import { Route as MerchantIndexRouteImport } from './routes/merchant/index'
import { Route as MerchantConnectionIdRouteImport } from './routes/merchant/$connectionId'
import { Route as MerchantLogRouteImport } from './routes/merchant/log'
import { Route as MerchantNewRouteImport } from './routes/merchant/new'
import { Route as MerchantNotificationsRouteImport } from './routes/merchant/notifications'
import { Route as MerchantQrRouteImport } from './routes/merchant/qr'
import { Route as MerchantRecordRouteImport } from './routes/merchant/record'
import { Route as MerchantScanRouteImport } from './routes/merchant/scan'
import { Route as MerchantSettingsRouteImport } from './routes/merchant/settings'
import { Route as RTokenRouteImport } from './routes/r/$token'
import { Route as ShopMerchantIdRouteImport } from './routes/shop/$merchantId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiInvoicesIndexRouteImport } from './routes/api/invoices/index'
import { Route as ApiInvoicesInvoiceIdRouteImport } from './routes/api/invoices/$invoiceId'
import { Route as CustomerApproveTransactionIdRouteImport } from './routes/customer/approve/$transactionId'
import { Route as CustomerPayConnectionIdRouteImport } from './routes/customer/pay/$connectionId'
import { Route as MerchantTermsConnectionIdRouteImport } from './routes/merchant/terms/$connectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRouteRoute = CustomerRouteRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRouteRoute = MerchantRouteRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerConnectionIdRoute = CustomerConnectionIdRouteImport.update({
  id: '/$connectionId',
  path: '/$connectionId',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerCardRoute = CustomerCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const InvoiceInvoiceIdRoute = InvoiceInvoiceIdRouteImport.update({
  id: '/invoice/$invoiceId',
  path: '/invoice/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantConnectionIdRoute = MerchantConnectionIdRouteImport.update({
  id: '/$connectionId',
  path: '/$connectionId',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantLogRoute = MerchantLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantNewRoute = MerchantNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantNotificationsRoute = MerchantNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantQrRoute = MerchantQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantRecordRoute = MerchantRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantScanRoute = MerchantScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantSettingsRoute = MerchantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopMerchantIdRoute = ShopMerchantIdRouteImport.update({
  id: '/shop/$merchantId',
  path: '/shop/$merchantId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicesIndexRoute = ApiInvoicesIndexRouteImport.update({
  id: '/api/invoices/',
  path: '/api/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicesInvoiceIdRoute = ApiInvoicesInvoiceIdRouteImport.update({
  id: '/api/invoices/$invoiceId',
  path: '/api/invoices/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerApproveTransactionIdRoute =
  CustomerApproveTransactionIdRouteImport.update({
    id: '/approve/$transactionId',
    path: '/approve/$transactionId',
    getParentRoute: () => CustomerRouteRoute,
  } as any)
const CustomerPayConnectionIdRoute = CustomerPayConnectionIdRouteImport.update({
  id: '/pay/$connectionId',
  path: '/pay/$connectionId',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const MerchantTermsConnectionIdRoute =
  MerchantTermsConnectionIdRouteImport.update({
    id: '/terms/$connectionId',
    path: '/terms/$connectionId',
    getParentRoute: () => MerchantRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteRouteWithChildren
  '/merchant': typeof MerchantRouteRouteWithChildren
  '/design': typeof DesignRoute
  '/sign-in': typeof SignInRoute
  '/status': typeof StatusRoute
  '/welcome': typeof WelcomeRoute
  '/api/events': typeof ApiEventsRoute
  '/customer/$connectionId': typeof CustomerConnectionIdRoute
  '/customer/card': typeof CustomerCardRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/invoice/$invoiceId': typeof InvoiceInvoiceIdRoute
  '/merchant/$connectionId': typeof MerchantConnectionIdRoute
  '/merchant/log': typeof MerchantLogRoute
  '/merchant/new': typeof MerchantNewRoute
  '/merchant/notifications': typeof MerchantNotificationsRoute
  '/merchant/qr': typeof MerchantQrRoute
  '/merchant/record': typeof MerchantRecordRoute
  '/merchant/scan': typeof MerchantScanRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/r/$token': typeof RTokenRoute
  '/shop/$merchantId': typeof ShopMerchantIdRoute
  '/customer/': typeof CustomerIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invoices/$invoiceId': typeof ApiInvoicesInvoiceIdRoute
  '/customer/approve/$transactionId': typeof CustomerApproveTransactionIdRoute
  '/customer/pay/$connectionId': typeof CustomerPayConnectionIdRoute
  '/merchant/terms/$connectionId': typeof MerchantTermsConnectionIdRoute
  '/api/invoices/': typeof ApiInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/sign-in': typeof SignInRoute
  '/status': typeof StatusRoute
  '/welcome': typeof WelcomeRoute
  '/api/events': typeof ApiEventsRoute
  '/customer/$connectionId': typeof CustomerConnectionIdRoute
  '/customer/card': typeof CustomerCardRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/invoice/$invoiceId': typeof InvoiceInvoiceIdRoute
  '/merchant/$connectionId': typeof MerchantConnectionIdRoute
  '/merchant/log': typeof MerchantLogRoute
  '/merchant/new': typeof MerchantNewRoute
  '/merchant/notifications': typeof MerchantNotificationsRoute
  '/merchant/qr': typeof MerchantQrRoute
  '/merchant/record': typeof MerchantRecordRoute
  '/merchant/scan': typeof MerchantScanRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/r/$token': typeof RTokenRoute
  '/shop/$merchantId': typeof ShopMerchantIdRoute
  '/customer': typeof CustomerIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invoices/$invoiceId': typeof ApiInvoicesInvoiceIdRoute
  '/customer/approve/$transactionId': typeof CustomerApproveTransactionIdRoute
  '/customer/pay/$connectionId': typeof CustomerPayConnectionIdRoute
  '/merchant/terms/$connectionId': typeof MerchantTermsConnectionIdRoute
  '/api/invoices': typeof ApiInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteRouteWithChildren
  '/merchant': typeof MerchantRouteRouteWithChildren
  '/design': typeof DesignRoute
  '/sign-in': typeof SignInRoute
  '/status': typeof StatusRoute
  '/welcome': typeof WelcomeRoute
  '/api/events': typeof ApiEventsRoute
  '/customer/$connectionId': typeof CustomerConnectionIdRoute
  '/customer/card': typeof CustomerCardRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/invoice/$invoiceId': typeof InvoiceInvoiceIdRoute
  '/merchant/$connectionId': typeof MerchantConnectionIdRoute
  '/merchant/log': typeof MerchantLogRoute
  '/merchant/new': typeof MerchantNewRoute
  '/merchant/notifications': typeof MerchantNotificationsRoute
  '/merchant/qr': typeof MerchantQrRoute
  '/merchant/record': typeof MerchantRecordRoute
  '/merchant/scan': typeof MerchantScanRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/r/$token': typeof RTokenRoute
  '/shop/$merchantId': typeof ShopMerchantIdRoute
  '/customer/': typeof CustomerIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invoices/$invoiceId': typeof ApiInvoicesInvoiceIdRoute
  '/customer/approve/$transactionId': typeof CustomerApproveTransactionIdRoute
  '/customer/pay/$connectionId': typeof CustomerPayConnectionIdRoute
  '/merchant/terms/$connectionId': typeof MerchantTermsConnectionIdRoute
  '/api/invoices/': typeof ApiInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer'
    | '/merchant'
    | '/design'
    | '/sign-in'
    | '/status'
    | '/welcome'
    | '/api/events'
    | '/customer/$connectionId'
    | '/customer/card'
    | '/customer/notifications'
    | '/invoice/$invoiceId'
    | '/merchant/$connectionId'
    | '/merchant/log'
    | '/merchant/new'
    | '/merchant/notifications'
    | '/merchant/qr'
    | '/merchant/record'
    | '/merchant/scan'
    | '/merchant/settings'
    | '/r/$token'
    | '/shop/$merchantId'
    | '/customer/'
    | '/merchant/'
    | '/api/auth/$'
    | '/api/invoices/$invoiceId'
    | '/customer/approve/$transactionId'
    | '/customer/pay/$connectionId'
    | '/merchant/terms/$connectionId'
    | '/api/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/sign-in'
    | '/status'
    | '/welcome'
    | '/api/events'
    | '/customer/$connectionId'
    | '/customer/card'
    | '/customer/notifications'
    | '/invoice/$invoiceId'
    | '/merchant/$connectionId'
    | '/merchant/log'
    | '/merchant/new'
    | '/merchant/notifications'
    | '/merchant/qr'
    | '/merchant/record'
    | '/merchant/scan'
    | '/merchant/settings'
    | '/r/$token'
    | '/shop/$merchantId'
    | '/customer'
    | '/merchant'
    | '/api/auth/$'
    | '/api/invoices/$invoiceId'
    | '/customer/approve/$transactionId'
    | '/customer/pay/$connectionId'
    | '/merchant/terms/$connectionId'
    | '/api/invoices'
  id:
    | '__root__'
    | '/'
    | '/customer'
    | '/merchant'
    | '/design'
    | '/sign-in'
    | '/status'
    | '/welcome'
    | '/api/events'
    | '/customer/$connectionId'
    | '/customer/card'
    | '/customer/notifications'
    | '/invoice/$invoiceId'
    | '/merchant/$connectionId'
    | '/merchant/log'
    | '/merchant/new'
    | '/merchant/notifications'
    | '/merchant/qr'
    | '/merchant/record'
    | '/merchant/scan'
    | '/merchant/settings'
    | '/r/$token'
    | '/shop/$merchantId'
    | '/customer/'
    | '/merchant/'
    | '/api/auth/$'
    | '/api/invoices/$invoiceId'
    | '/customer/approve/$transactionId'
    | '/customer/pay/$connectionId'
    | '/merchant/terms/$connectionId'
    | '/api/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRouteRoute: typeof CustomerRouteRouteWithChildren
  MerchantRouteRoute: typeof MerchantRouteRouteWithChildren
  DesignRoute: typeof DesignRoute
  SignInRoute: typeof SignInRoute
  StatusRoute: typeof StatusRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiEventsRoute: typeof ApiEventsRoute
  InvoiceInvoiceIdRoute: typeof InvoiceInvoiceIdRoute
  RTokenRoute: typeof RTokenRoute
  ShopMerchantIdRoute: typeof ShopMerchantIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInvoicesInvoiceIdRoute: typeof ApiInvoicesInvoiceIdRoute
  ApiInvoicesIndexRoute: typeof ApiInvoicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/$connectionId': {
      id: '/customer/$connectionId'
      path: '/$connectionId'
      fullPath: '/customer/$connectionId'
      preLoaderRoute: typeof CustomerConnectionIdRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/card': {
      id: '/customer/card'
      path: '/card'
      fullPath: '/customer/card'
      preLoaderRoute: typeof CustomerCardRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/invoice/$invoiceId': {
      id: '/invoice/$invoiceId'
      path: '/invoice/$invoiceId'
      fullPath: '/invoice/$invoiceId'
      preLoaderRoute: typeof InvoiceInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/$connectionId': {
      id: '/merchant/$connectionId'
      path: '/$connectionId'
      fullPath: '/merchant/$connectionId'
      preLoaderRoute: typeof MerchantConnectionIdRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/log': {
      id: '/merchant/log'
      path: '/log'
      fullPath: '/merchant/log'
      preLoaderRoute: typeof MerchantLogRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/new': {
      id: '/merchant/new'
      path: '/new'
      fullPath: '/merchant/new'
      preLoaderRoute: typeof MerchantNewRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/notifications': {
      id: '/merchant/notifications'
      path: '/notifications'
      fullPath: '/merchant/notifications'
      preLoaderRoute: typeof MerchantNotificationsRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/qr': {
      id: '/merchant/qr'
      path: '/qr'
      fullPath: '/merchant/qr'
      preLoaderRoute: typeof MerchantQrRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/record': {
      id: '/merchant/record'
      path: '/record'
      fullPath: '/merchant/record'
      preLoaderRoute: typeof MerchantRecordRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/scan': {
      id: '/merchant/scan'
      path: '/scan'
      fullPath: '/merchant/scan'
      preLoaderRoute: typeof MerchantScanRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/settings': {
      id: '/merchant/settings'
      path: '/settings'
      fullPath: '/merchant/settings'
      preLoaderRoute: typeof MerchantSettingsRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$merchantId': {
      id: '/shop/$merchantId'
      path: '/shop/$merchantId'
      fullPath: '/shop/$merchantId'
      preLoaderRoute: typeof ShopMerchantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoices/': {
      id: '/api/invoices/'
      path: '/api/invoices'
      fullPath: '/api/invoices/'
      preLoaderRoute: typeof ApiInvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoices/$invoiceId': {
      id: '/api/invoices/$invoiceId'
      path: '/api/invoices/$invoiceId'
      fullPath: '/api/invoices/$invoiceId'
      preLoaderRoute: typeof ApiInvoicesInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/approve/$transactionId': {
      id: '/customer/approve/$transactionId'
      path: '/approve/$transactionId'
      fullPath: '/customer/approve/$transactionId'
      preLoaderRoute: typeof CustomerApproveTransactionIdRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/pay/$connectionId': {
      id: '/customer/pay/$connectionId'
      path: '/pay/$connectionId'
      fullPath: '/customer/pay/$connectionId'
      preLoaderRoute: typeof CustomerPayConnectionIdRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/merchant/terms/$connectionId': {
      id: '/merchant/terms/$connectionId'
      path: '/terms/$connectionId'
      fullPath: '/merchant/terms/$connectionId'
      preLoaderRoute: typeof MerchantTermsConnectionIdRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
  }
}

interface CustomerRouteRouteChildren {
  CustomerConnectionIdRoute: typeof CustomerConnectionIdRoute
  CustomerCardRoute: typeof CustomerCardRoute
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerApproveTransactionIdRoute: typeof CustomerApproveTransactionIdRoute
  CustomerPayConnectionIdRoute: typeof CustomerPayConnectionIdRoute
}

const CustomerRouteRouteChildren: CustomerRouteRouteChildren = {
  CustomerConnectionIdRoute: CustomerConnectionIdRoute,
  CustomerCardRoute: CustomerCardRoute,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerApproveTransactionIdRoute: CustomerApproveTransactionIdRoute,
  CustomerPayConnectionIdRoute: CustomerPayConnectionIdRoute,
}

const CustomerRouteRouteWithChildren = CustomerRouteRoute._addFileChildren(
  CustomerRouteRouteChildren,
)

interface MerchantRouteRouteChildren {
  MerchantConnectionIdRoute: typeof MerchantConnectionIdRoute
  MerchantLogRoute: typeof MerchantLogRoute
  MerchantNewRoute: typeof MerchantNewRoute
  MerchantNotificationsRoute: typeof MerchantNotificationsRoute
  MerchantQrRoute: typeof MerchantQrRoute
  MerchantRecordRoute: typeof MerchantRecordRoute
  MerchantScanRoute: typeof MerchantScanRoute
  MerchantSettingsRoute: typeof MerchantSettingsRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
  MerchantTermsConnectionIdRoute: typeof MerchantTermsConnectionIdRoute
}

const MerchantRouteRouteChildren: MerchantRouteRouteChildren = {
  MerchantConnectionIdRoute: MerchantConnectionIdRoute,
  MerchantLogRoute: MerchantLogRoute,
  MerchantNewRoute: MerchantNewRoute,
  MerchantNotificationsRoute: MerchantNotificationsRoute,
  MerchantQrRoute: MerchantQrRoute,
  MerchantRecordRoute: MerchantRecordRoute,
  MerchantScanRoute: MerchantScanRoute,
  MerchantSettingsRoute: MerchantSettingsRoute,
  MerchantIndexRoute: MerchantIndexRoute,
  MerchantTermsConnectionIdRoute: MerchantTermsConnectionIdRoute,
}

const MerchantRouteRouteWithChildren = MerchantRouteRoute._addFileChildren(
  MerchantRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRouteRoute: CustomerRouteRouteWithChildren,
  MerchantRouteRoute: MerchantRouteRouteWithChildren,
  DesignRoute: DesignRoute,
  SignInRoute: SignInRoute,
  StatusRoute: StatusRoute,
  WelcomeRoute: WelcomeRoute,
  ApiEventsRoute: ApiEventsRoute,
  InvoiceInvoiceIdRoute: InvoiceInvoiceIdRoute,
  RTokenRoute: RTokenRoute,
  ShopMerchantIdRoute: ShopMerchantIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInvoicesInvoiceIdRoute: ApiInvoicesInvoiceIdRoute,
  ApiInvoicesIndexRoute: ApiInvoicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
